# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
#      - name: Tests
#        run: flutter test .
      - name: Dry Run
        run: flutter pub publish --dry-run
      - name: Publish
        run: dart pub publish --force